
export default {

  CHANGE_EVENT: 'change',
  CREATE_CHANNEL_EVENT: 'channel',

  DEFAULT_CHANNEL: 'general',

  ActionTypes: {
    AUTH_USER: 'AUTH_USER',
    CONNECT_CHAT: 'CONNECT_CHAT',
    FETCH_USER: 'FETCH_USER',
    ENTER_MESSAGE: 'ENTER_MESSAGE',
    OPEN_CREATE_CHANNEL: 'OPEN_CREATE_CHANNEL',
    CLOSE_CREATE_CHANNEL: 'CLOSE_CREATE_CHANNEL',
    CREATE_CHANNEL: 'CREATE_CHANNEL',
    SIGN_OUT: 'SIGN_OUT',
    LEAVE_CHANNEL: 'LEAVE_CHANNEL',
    CHANGE_CHANNEL: 'CHANGE_CHANNEL'
  }

}
